### ISSUE TITLE
Picker无法设置选择样式

### ISSUE THREAD

**Issue by 2linziyi2** [ant-design/ant-design-mobile-rn#1072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Picker应该增加选中样式。一般我们希望选中字体颜色和app的主题色保持一致，并且我们希望每行高度也可以自定义。

### What does the proposed API look like?
selectItemStyles

**Comment by 1uokun** [comment]
组件设计参考自`@react-native-community/picker`,可以通过`itemStyle`修改所有的。
但是被选中的目前只是加粗了而已，详见`picker/NativePicker.android.js`
```css
  selectedItemText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
  }
```
